### ISSUE TITLE
Don't download undownloadable comics

### ISSUE THREAD

**Issue by Kaligule** [keatinge/XKCD-Downloader#1]
Some xkcd comics are just not trivialy downloadable, for example [1110](https://xkcd.com/1110/).
There should be a list of this comics, so they can be identified and not be downloaded.

**Comment by keatinge** [comment]
@Kaligule Good point, I just wish there was some better solution than keeping a list of non downloadable comics. Maybe it's possible to figure out if the comic is downloadable by checking for something in HTML?

**Comment by SquishyStrawberry** [comment]
@keatinge Usually most *undownloadable* comics have more than an `<img>` tag in the comic `<div>`, and I think in the case of [404](https://xkcd.com/404/) it will be caught already by the error-checking already present.

**Comment by SquishyStrawberry** [comment]
@keatinge You should close this.
